import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import { PrintDisclaimer } from "../../src/components/PrintPage/PrintDisclaimer";
import { PrintPageFooter } from "../../src/components/PrintPage/PrintPageFooter";
import { PrintPageGenerated } from "../../src/components/PrintPage/PrintPageGenerated";
import { PrintPageHeader } from "../../src/components/PrintPage/PrintPageHeader";
import { PRINT_META_SEPARATOR } from "../../src/components/PrintPage/printPageMeta";

describe("PrintPage chrome", () => {
  it("renders the template header with company logo, company, document type, id, revision and issued date", () => {
    render(
      <PrintPageHeader
        companyName="BKN JET"
        logoSrc="https://example.com/files/logo.png"
        config={{
          documentType: "Safety Risk Assessment Record",
          title: "Flight Safety Risks in Conflict Areas",
          number: "BKN-SR-1009",
          revision: 0,
          date: "2026/07/27",
        }}
      />,
    );

    expect(screen.getByRole("img", { name: "Company logo" })).toHaveAttribute(
      "src",
      "https://example.com/files/logo.png",
    );
    expect(screen.getByText("BKN JET")).toBeInTheDocument();
    expect(
      screen.getByText("Safety Risk Assessment Record"),
    ).toBeInTheDocument();
    expect(
      screen.queryByText("Flight Safety Risks in Conflict Areas"),
    ).not.toBeInTheDocument();
    expect(screen.getByText("BKN-SR-1009")).toBeInTheDocument();
    expect(screen.getByText(/Rev\. 00/)).toBeInTheDocument();
    expect(screen.getByText(/Issued 2026\/07\/27/)).toBeInTheDocument();
  });

  it("renders footer identity, page pagination slot, and the uncontrolled notice", () => {
    render(
      <PrintPageFooter
        companyName="BKN JET"
        documentType="Safety Risk Report"
        documentId="BKN-SR-1009"
        isUncontrolledDocument
      />,
    );

    expect(
      screen.getByText(
        `BKN JET${PRINT_META_SEPARATOR}Safety Risk Report${PRINT_META_SEPARATOR}BKN-SR-1009`,
      ),
    ).toBeInTheDocument();
    expect(
      document.querySelector(".print-page-footer__pagination"),
    ).toBeInTheDocument();
    expect(screen.getByText("Control Not Established")).toHaveClass(
      "print-page-footer__notice",
      "uncontrolled-document-print-notice",
    );
  });

  it("renders PrintDisclaimer with the template uncontrolled copy", () => {
    const { rerender } = render(
      <PrintDisclaimer isUncontrolledDocument={false} />,
    );
    expect(
      screen.queryByText("Control Not Established"),
    ).not.toBeInTheDocument();

    rerender(<PrintDisclaimer isUncontrolledDocument />);
    expect(screen.getByText("Control Not Established")).toBeInTheDocument();
  });

  it("omits the uncontrolled notice when the document is controlled", () => {
    render(
      <PrintPageFooter
        companyName="BKN JET"
        documentType="Safety Risk Report"
        documentId="BKN-SR-1009"
        isUncontrolledDocument={false}
      />,
    );

    expect(
      screen.queryByText("Control Not Established"),
    ).not.toBeInTheDocument();
    expect(
      document.querySelector(".print-page-footer__pagination"),
    ).toBeInTheDocument();
  });

  it("renders the vertical generated-by mark", () => {
    render(<PrintPageGenerated />);

    const mark = screen.getByText("Generated by");
    expect(mark).toHaveClass("print-page-generated__text");
    expect(mark.parentElement).toHaveClass("print-page-generated");
  });
});
