import type {
  CSSProperties,
  ForwardRefExoticComponent,
  HTMLAttributes,
  ReactNode,
  RefAttributes,
  RefObject,
} from "react";
import type { UseReactToPrintFn, UseReactToPrintOptions } from "react-to-print";
import type { PrintTableColumn, PrintTableRow } from "../components/tablePrint";
import type {
  PageConfig,
  PageNumberConfig,
  PrintTheme,
  TextDirection,
  WatermarkConfig,
} from "./page";
import type { PrintFontPageStyleOptions } from "../utils/printPageStyle";

export type {
  PageSize,
  Orientation,
  PageMargin,
  PageConfig,
  PageNumberConfig,
  WatermarkConfig,
  PrintTheme,
  TextDirection,
} from "./page";

export type PrintPageHeaderConfig = {
  revision?: string | number;
  number?: string | number;
  prefix?: string | number;
  title?: string;
  documentType?: string;
  date?: string | number;
};

export type PrintBranding = {
  /** Plain image URL (http(s), data:, blob:, or relative path). */
  logoSrc?: string | null;
  companyName?: string | null;
  /**
   * Label used in the footer identity line. The template prints the short
   * report name there ("Safety Risk Report") while the header kicker carries
   * the long document type ("Safety Risk Assessment Record"). Falls back to
   * the header document type when omitted.
   */
  reportType?: string | null;
  /** Override for the vertical "generated by" mark. */
  generatedByLabel?: string;
  /** Override for the uncontrolled-document footer notice. */
  uncontrolledLabel?: string;
};

export type PrintFromRefOptions<T extends HTMLElement = HTMLDivElement> = Omit<
  UseReactToPrintOptions,
  "contentRef"
> & {
  contentRef?: RefObject<T | null>;
  /** @deprecated Prefer `title`. Still forwarded to react-to-print as documentTitle. */
  documentTitle?: string;
  /** Document title used for the print job / PDF filename fallback. */
  title?: string;
  pageHeader?: PrintPageHeaderConfig;
  branding?: PrintBranding;
  /** Page size, orientation, and margins. Defaults to A4 portrait. */
  page?: PageConfig;
  direction?: TextDirection;
  pageNumber?: PageNumberConfig;
  watermark?: WatermarkConfig;
  theme?: PrintTheme;
  font?: PrintFontPageStyleOptions;
  /** Custom header node rendered instead of the default PrintPageHeader. */
  header?: ReactNode;
  /** Custom footer node rendered instead of the default PrintPageFooter. */
  footer?: ReactNode;
};

export type PrintableRootProps = {
  children?: ReactNode;
  className?: string;
  id?: string;
  style?: CSSProperties;
} & HTMLAttributes<HTMLDivElement>;

export type PrintableRootComponent = ForwardRefExoticComponent<
  PrintableRootProps & RefAttributes<HTMLDivElement>
>;

export interface PrintWorkspaceContextValue {
  isUncontrolledDocument: boolean;
  logo?: string | null;
}

export type ExportPdfOptions = {
  filename?: string;
  /** @deprecated Prefer `filename`. */
  fileName?: string;
  /** Pixel scale for rasterization. Default 2. */
  scale?: number;
  /** JPEG quality 0–1 when using JPEG. Default 0.92. */
  imageQuality?: number;
};

export type PreviewOptions = {
  open?: boolean;
};

export type UsePrintFromRefWithRootResult = {
  print: UseReactToPrintFn;
  exportPdf: (options?: ExportPdfOptions) => Promise<void>;
  preview: (options?: PreviewOptions) => void;
  closePreview: () => void;
  isPreviewOpen: boolean;
  PrintableRoot: PrintableRootComponent;
  PreviewPortal: () => ReactNode;
};

/** @deprecated Use ExportPdfOptions with usePrintFromRef().exportPdf. */
export type ExportPdfFromRefOptions<T extends HTMLElement = HTMLDivElement> = {
  contentRef?: RefObject<T | null>;
  pageHeader?: PrintPageHeaderConfig;
  fileName?: string;
  documentTitle?: string;
};

/** @deprecated Use UsePrintFromRefWithRootResult. */
export type UseExportPdfFromRefWithRootResult = {
  exportPdf: () => Promise<void>;
  PrintableRoot: PrintableRootComponent;
};

export type PrintFromRefTableData = {
  meta?: ReactNode;
  columns: PrintTableColumn[];
  rows: PrintTableRow[];
  className?: string;
  columnWidths?: string[];
  totals?: PrintTableRow[];
  subtotal?: PrintTableRow;
  summary?: PrintTableRow[];
};
