import type { PrintHistoryLabels } from "./components/PrintPage/PrintHistorySection";

/** Default English copy used when no custom labels are passed. */
export const DEFAULT_PRINT_LABELS = {
  generatedBy: "Generated by",
  uncontrolledWhenPrinted: "Control Not Established",
  logoAlt: "Company logo",
  documentHeader: "Document",
  revision: (revision: string) => `Rev. ${revision}`,
  issued: (date: string) => `Issued ${date}`,
  page: "Page",
  of: "of",
  print: "Print",
  close: "Close",
  downloadPdf: "Download PDF",
  preview: "Preview",
  pageNumberFormat: "Page {current} of {total}",
} as const;

export const DEFAULT_PRINT_HISTORY_LABELS: PrintHistoryLabels = {
  title: "Activity history",
  empty: "No activity recorded.",
  date: "Date",
  actor: "By",
  action: "Action",
  detail: "Detail",
};

export function formatPageNumber(
  format: string,
  current: number | string,
  total: number | string,
): string {
  return format
    .split("{current}")
    .join(String(current))
    .split("{total}")
    .join(String(total));
}
